<?php
/**
 * @author      Sam Mahoney for Meab
 * @copyright   Copyright (C) 2016 - Meab
 */
?>

<?php if(count($this->getItemCollection()->getItems())): ?>
<?php $_columnCount = 5; ?>
<div class="box-collateral box-up-sell">
    <h2><?php echo $this->__('Related Products') ?></h2>
    <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col" id="upsell-product-table">
    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php $i=0; foreach ($this->getItemCollection()->getItems() as $_link): if($i<5): ?>
    <?php /*for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <tr>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): */ ?>
        <li class="item-<?php echo $i; ?>">
            <a href="<?php echo $_link->getProductUrl() ?>" class="product-image">
                <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(460,690) ?>" alt="<?php echo $this->escapeHtml($_link->getName()) ?>" />
            </a>
            <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_link->getName()) ?>"><?php echo $this->escapeHtml($_link->getName()) ?></a></h3>
            <div class="details"><?php if($_link->getColor()): echo $_link->getResource()->getAttribute('color')->getFrontend()->getValue($_link); endif; ?></div>
            <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
            <?php echo $this->getReviewsSummaryHtml($_link) ?>
        </li>
            <?php /*else: ?>
            <td class="empty">&nbsp;</td>
            <?php endif; ?>
        <?php endfor; ?>
        </tr>
    <?php endfor; */?>
    <?php $i++; endif; endforeach; ?>
    </ul>
    <?php /*
    <script type="text/javascript">decorateGeneric($$('#upsell-product-table'), ['odd','even','first','last'])</script>
    */ ?>
</div>
<?php endif ?>
