<?php
/**
 * @author      Sam Mahoney for Meab
 * @copyright   Copyright (C) 2016 - Meab
 */
/* @var $this Mage_Reports_Block_Product_Viewed */
?>

<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="footer-container product-view">
    <div class="box-collateral box-up-sell">
        <h2><?php echo $this->__('Recently Viewed Products') ?></h2>
        <ul class="products-grid products-grid--max-5-col" id="upsell-product-table">
        <?php foreach ($_products as $_link): ?>
            <li class="item-<?php echo $i; ?>">
                <a href="<?php echo $_link->getProductUrl() ?>" class="product-image">
                    <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(460) ?>" alt="<?php echo $this->escapeHtml($_link->getName()) ?>" />
                </a>
                <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_link->getName()) ?>"><?php echo $this->escapeHtml($_link->getName()) ?></a></h3>
                <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
                <?php echo $this->getReviewsSummaryHtml($_link) ?>
            </li>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('recently-viewed-items');</script>
    </div>
</div>
<?php endif; ?>
